### ISSUE TITLE
Kibana6.6.1版本运行 plugin 时会报错

### ISSUE THREAD

**Issue by weichaojie** [TrumanDu/indices_view#9]
Debug: internal, implementation, error 
    Error: handler method did not return a value, a promise, or throw an error
    at module.exports.internals.Manager.execute (/Users//kibana/node_modules/hapi/lib/toolkit.js:52:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
server   error  [05:54:22.223]  Error: handler method did not return a value, a promise, or throw an error
    at module.exports.internals.Manager.execute (/Users/kibana/node_modules/hapi/lib/toolkit.js:52:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)

/Users/kibana/node_modules/elasticsearch/src/lib/transport.js:329
        cb(void 0, parsedBody, status);
        ^
TypeError: reply is not a function
    at /Users/kibana/plugins/indices_view/server/routes/serverRoute.js:13:11
    at respond (/Users/kibana/node_modules/elasticsearch/src/lib/transport.js:329:9)
    at checkRespForFailure (/Users/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/Users/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/Users/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
 server crashed  with status code 1

**Comment by TrumanDu** [comment]
I will fix it! thanks for u

**Comment by TrumanDu** [comment]
@weichaojie 因为版本升级，hapi用法发生变化，以及kibana配置文件属性发生变化，现已更正代码。详见[最新发布版本](https://github.com/TrumanDu/indices_view/releases/tag/v6.6.1)
